apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
  namespace: exp
spec:
  selector:
    matchLabels:
      app: blog-deploy
  template:
    metadata:
      labels:
        app: blog-deploy
    spec:
      imagePullSecrets:
        - name: blog-registry
      containers:
      - name: blog-deploy
        image: registry.cn-beijing.aliyuncs.com/strk2/strk2-blog:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 40m
            memory: 40Mi
          limits:
            cpu: 40m
            memory: 40Mi
        ports:
        - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: blogsvc
spec:
  selector:
    app: blog-deploy
  ports:
    - port: 80
      targetPort: 80
      name: blog-deploy