name: Docker Image CI
env:
  AZURE_WEBAPP_NAME: blog # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "10.x"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: 盐焗乳鸽还要香锅
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.cn-beijing.aliyuncs.com/strk2/strk2-blog
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop $(docker ps --filter ancestor=registry.cn-beijing.aliyuncs.com/strk2/strk2-blog -q)
            docker rm -f $(docker ps -a --filter ancestor=registry.cn-beijing.aliyuncs.com/strk2/strk2-blog:latest -q)
            docker rmi -f $(docker images registry.cn-beijing.aliyuncs.com/strk2/strk2-blog:latest -q)
            docker login --username=盐焗乳鸽还要香锅 --password=${{ secrets.PASSWORD }} registry.cn-beijing.aliyuncs.com
            docker pull registry.cn-beijing.aliyuncs.com/strk2/strk2-blog
            docker run -dt -p 80:80 registry.cn-beijing.aliyuncs.com/strk2/strk2-blog
